INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('17', 'Image', 'Stemma', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="17"><descr>Stemma</descr><groups mainGroup="free" /><categories /><masterfile>stemma.jpg</masterfile><instance><size>3</size><filename>stemma_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>2</size><filename>stemma_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>1</size><filename>stemma_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>stemma_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>130 Kb</weight></instance></resource>
', 'stemma.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('19', 'Attach', 'Bando Lavori Manutenzione Istituto Nautico', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="19"><descr>Bando Lavori Manutenzione Istituto Nautico</descr><groups mainGroup="free" /><categories /><masterfile>Bando_manutenzione_istituto_nautico.pdf</masterfile><instance><size>0</size><filename>Bando_manutenzione_istituto_nautico.pdf</filename><mimetype>application/pdf</mimetype><weight>25 Kb</weight></instance></resource>
', 'Bando_manutenzione_istituto_nautico.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('21', 'Attach', 'Bando Fornitura Cancelleria', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="21"><descr>Bando Fornitura Cancelleria</descr><groups mainGroup="free" /><categories /><masterfile>Bando_fornitura_cancelleria.pdf</masterfile><instance><size>0</size><filename>Bando_fornitura_cancelleria.pdf</filename><mimetype>application/pdf</mimetype><weight>24 Kb</weight></instance></resource>
', 'Bando_fornitura_cancelleria.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('23', 'Attach', 'Bando Servizio Civile', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="23"><descr>Bando Servizio Civile</descr><groups mainGroup="free" /><categories /><masterfile>Bando_servizio_civile.pdf</masterfile><instance><size>0</size><filename>Bando_servizio_civile.pdf</filename><mimetype>application/pdf</mimetype><weight>29 Kb</weight></instance></resource>
', 'Bando_servizio_civile.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('25', 'Attach', 'Resolution 15', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="25"><descr>Resolution 15</descr><groups mainGroup="free" /><categories /><masterfile>Delibera_15.pdf</masterfile><instance><size>0</size><filename>Delibera_15.pdf</filename><mimetype>application/pdf</mimetype><weight>16 Kb</weight></instance></resource>
', 'Delibera_15.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('27', 'Attach', 'Resolution 120', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="27"><descr>Resolution 120</descr><groups mainGroup="free" /><categories /><masterfile>Delibera_120.pdf</masterfile><instance><size>0</size><filename>Delibera_120.pdf</filename><mimetype>application/pdf</mimetype><weight>16 Kb</weight></instance></resource>
', 'Delibera_120.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('29', 'Attach', 'Resolution 20', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="29"><descr>Resolution 20</descr><groups mainGroup="free" /><categories /><masterfile>Delibera_20.pdf</masterfile><instance><size>0</size><filename>Delibera_20.pdf</filename><mimetype>application/pdf</mimetype><weight>16 Kb</weight></instance></resource>
', 'Delibera_20.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('31', 'Attach', 'Resolution 133', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="31"><descr>Resolution 133</descr><groups mainGroup="free" /><categories /><masterfile>Delibera_133.pdf</masterfile><instance><size>0</size><filename>Delibera_133.pdf</filename><mimetype>application/pdf</mimetype><weight>16 Kb</weight></instance></resource>
', 'Delibera_133.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('35', 'Attach', 'Bando Locazione', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="35"><descr>Bando Locazione</descr><groups mainGroup="free" /><categories /><masterfile>Bando_canone_locazione.pdf</masterfile><instance><size>0</size><filename>Bando_canone_locazione.pdf</filename><mimetype>application/pdf</mimetype><weight>17 Kb</weight></instance></resource>
', 'Bando_canone_locazione.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('36', 'Attach', 'Modulo Domanda Locazione', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="36"><descr>Modulo Domanda Locazione</descr><groups mainGroup="free" /><categories /><masterfile>Modulo_domanda_contributo_canone_locazione.pdf</masterfile><instance><size>0</size><filename>Modulo_domanda_contributo_canone_locazione.pdf</filename><mimetype>application/pdf</mimetype><weight>17 Kb</weight></instance></resource>
', 'Modulo_domanda_contributo_canone_locazione.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('38', 'Image', 'A beautiful view of Entando Town', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="38"><descr>A beautiful view of Entando Town</descr><groups mainGroup="free" /><categories /><masterfile>Immagine1.jpg</masterfile><instance><size>3</size><filename>Immagine1_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>6 Kb</weight></instance><instance><size>2</size><filename>Immagine1_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>1</size><filename>Immagine1_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>0</size><filename>Immagine1_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>3444 Kb</weight></instance></resource>
', 'Immagine1.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('42', 'Image', 'Walter Ambu', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="42"><descr>Walter Ambu</descr><groups mainGroup="free" /><categories /><masterfile>walterambu_1331060049_37.jpg</masterfile><instance><size>3</size><filename>walterambu_1331060049_37_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>walterambu_1331060049_37_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>walterambu_1331060049_37_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>walterambu_1331060049_37_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>93 Kb</weight></instance></resource>
', 'walterambu_1331060049_37.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('45', 'Attach', 'Statute', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="45"><descr>Statute</descr><groups mainGroup="free" /><categories /><masterfile>Statuto_Villamarina.pdf</masterfile><instance><size>0</size><filename>Statuto_Villamarina.pdf</filename><mimetype>application/pdf</mimetype><weight>19 Kb</weight></instance></resource>
', 'Statuto_Villamarina.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('47', 'Attach', 'Richiesta Carta Identità', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="47"><descr>Richiesta Carta Identità</descr><groups mainGroup="free" /><categories /><masterfile>Modulo_Richiesta_Carta_Identita.pdf</masterfile><instance><size>0</size><filename>Modulo_Richiesta_Carta_Identita.pdf</filename><mimetype>application/pdf</mimetype><weight>17 Kb</weight></instance></resource>
', 'Modulo_Richiesta_Carta_Identita.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('49', 'Attach', 'Modulo - richiesta rimborso ICI', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="49"><descr>Modulo - richiesta rimborso ICI</descr><groups mainGroup="free" /><categories /><masterfile>Modulo_Richiesta_Rimborso_ICI.pdf</masterfile><instance><size>0</size><filename>Modulo_Richiesta_Rimborso_ICI.pdf</filename><mimetype>application/pdf</mimetype><weight>17 Kb</weight></instance></resource>
', 'Modulo_Richiesta_Rimborso_ICI.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('51', 'Attach', 'Modulo Autocertificazione Stato Civile', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="51"><descr>Modulo Autocertificazione Stato Civile</descr><groups mainGroup="free" /><categories /><masterfile>Modulo_Certificato_Stato_Civile.pdf</masterfile><instance><size>0</size><filename>Modulo_Certificato_Stato_Civile.pdf</filename><mimetype>application/pdf</mimetype><weight>14 Kb</weight></instance></resource>
', 'Modulo_Certificato_Stato_Civile.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('53', 'Attach', 'Residence Self Certification Form', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="53"><descr>Residence Self Certification Form</descr><groups mainGroup="free" /><categories /><masterfile>Modulo_Certificato_Residenza.pdf</masterfile><instance><size>0</size><filename>Modulo_Certificato_Residenza.pdf</filename><mimetype>application/pdf</mimetype><weight>14 Kb</weight></instance></resource>
', 'Modulo_Certificato_Residenza.pdf');
